name: sikka_pay
description: >
  A lightweight, in-memory Dart SDK for simulating money transactions (deposit, withdraw, transfer),
  similar to a mobile money platform like Orange Money.
version: 1.0.0
repository: https://github.com/YannMartin123/sikka_pay

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
